# Generated by Django 3.0.5 on 2020-05-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premises',
            name='owner',
        ),
    ]
