# Generated by Django 3.0.4 on 2020-03-19 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('STARTED', 'STARTED'), (
                    'IN_PROGRESS', 'IN_PROGRESS'), ('READY', 'READY'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=20)),
            ],
        ),
    ]
