# Generated by Django 3.0.5 on 2020-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200619_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
