# Generated by Django 3.0.11 on 2020-12-30 18:27

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point
from django.contrib.postgres.operations import CreateExtension
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201229_1346'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.RemoveField(
            model_name='premises',
            name='image_url',
        ),
        migrations.AddField(
            model_name='premises',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premises',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premises',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='premises',
            name='image',
            field=models.FileField(default='', upload_to='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premises',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(0.0, 0.0), srid=4326, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premises',
            name='postcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premises',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='premises',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
