# Generated by Django 3.0.14 on 2021-06-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201230_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='order',
            name='premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='orders_as_premises', to='core.Premises'),
        ),
    ]
