# Generated by Django 3.0.14 on 2021-08-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210609_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premises',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_premises', to=settings.AUTH_USER_MODEL),
        ),
    ]
