name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest
    environment: waitless_backend

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        touch .env
        echo AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} >> .env
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
        cat .env
    - name: Build the stack
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: List Containers
      run: docker-compose ps -a
    - name: Wait for db and check connection
      run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py check_connection"
    - name: Run tests and flake8
      run: docker-compose run app sh -c "pytest && flake8"
